cleanup test files on test start

diff --git a/scripts/test-service b/scripts/test-service
--- a/scripts/test-service
+++ b/scripts/test-service
@@ -9,6 +9,11 @@ wait_for_init() {
   done
 }
 
+cleanup() {
+  rm -f /home/waggle/test_node_*.log /home/waggle/continue_test /home/waggle/finish_test /home/waggle/test-report.txt \
+        /media/test/home/waggle/*_test /media/test/home/waggle/test_node_*.log /media/test/home/waggle/test-report.txt
+}
+
 wait_for_gn_boot() {
   echo "In wait_for_gn_boot"
   local last_hb=0
@@ -51,14 +56,6 @@ wait_for_gn_reboot() {
 
 run_gn_tests() {
   echo "In run_gn_tests"
-
-  # wait for GN to power on
-  wait_for_gn_boot
-  exit_code=$?
-  if [ $exit_code -ne 0 ]; then
-    echo "ERROR: failed to detect a GN heartbeat after 2 minutes"
-    exit $exit_code
-  fi
 
   # Run tests on the SD or eMMC
   ssh -i /usr/lib/waggle/SSL/guest/id_rsa_waggle_aot_guest_node waggle@10.31.81.51 \
@@ -156,6 +153,14 @@ if [ ! -e ${init_file} ] ; then
   fi
 elif [ -e ${start_file} ] ; then
   echo "Found start_test."
+  # wait for GN to power on
+  wait_for_gn_boot
+  exit_code=$?
+  if [ $exit_code -ne 0 ]; then
+    echo "ERROR: failed to detect a GN heartbeat after 2 minutes"
+    exit $exit_code
+  fi
+  cleanup
   run_tests
   if [ "${CURRENT_DISK_DEVICE_TYPE}" == "SD" ]; then
     echo "Setting boot medium to eMMC..."
